puppetlabs/pxp-agent-vanagon

configs/platforms/osx-10.14-x86_64.rb
configs/platforms/osx-10.15-x86_64.rb

Boost already comes in puppet-runtime, we shouldn't need to install it.

(maint) Do not provision boost on OS X

---

configs/components/pxp-agent.rb

For consistency reasons, this PR moves pxp-agent.newsyslog.conf to the `osx` folder.

(maint) move pxp-agent.newsyslog.conf to {service_conf}/osx/

---

configs/platforms/debian-10-armhf.rb

This comit adds debian-10-armhf platform as a direct compile.
This requires https://github.com/puppetlabs/puppet-runtime/pull/420 first.

Add debian-10-armhf to pxp-agent

---

configs/platforms/debian-9-amd64.rb
configs/platforms/debian-9-i386.rb

Vanagon already defines systemd in the default
platform definition. Remove it from here to avoid
duplication.

(VANAGON-85) remove duplicate systemd on debian 9

---

configs/components/cleanup.rb

This file was previously included inline in a C++ source code file, but
it's now extracted to a Ruby file of its very own. So we shouldn't
delete it during the cleanup step.

(PA-3731) Package apply_ruby_shim.rb execution wrapper

---

configs/platforms/el-8-aarch64.rb
configs/platforms/el-8-ppc64le.rb
configs/platforms/el-8-x86_64.rb

https://github.com/puppetlabs/pxp-agent-vanagon/pull/25 locked cmake to 3.11.4 to overcome an issue with libarchive 3.3.2.
The issue was fixed in libarchive 3.3.1 bugs.centos.org/view.php?id=18212

(maint) install libarchive on el-8

---

configs/components/cpp-hocon.rb
configs/components/cpp-pcp-client.rb
configs/components/leatherman.rb
configs/components/pxp-agent.rb
configs/platforms/osx-11-arm64.rb

Add support for building the pxp-agent project for macOS 11 ARM64 (M1) via cross-compilation from an x86 host.

(PA-3829) Add macOS 11 arm64 platform

---

configs/components/cpp-hocon.json
configs/components/cpp-pcp-client.json
configs/components/leatherman.json
configs/components/nssm.json
configs/components/pxp-agent.json

Replacing Git protocol since it will no longer be supported.

(maint) PA-4182 replace git:// with https://

---

.github/workflows/snyk_monitor.yaml

This monitors the ruby gems that vanagon uses to build the C++ pxp-agent components. The generated artifact doesn't contain any gems.
See https://github.com/puppetlabs/pxp-agent-vanagon/runs/5515470085

(PA-4319) Snyk monitor pushes to main

---

configs/components/cpp-hocon.rb
configs/components/cpp-pcp-client.rb
configs/components/leatherman.rb
configs/components/pxp-agent.rb
configs/platforms/osx-12-arm64.rb

Add support for building the pxp-agent project for macOS 12 Monterey
ARM64 (M1) via cross-compilation on an x86-64 host.
Was able to successfully, manually build this.

(PA-4416) Add macOS 12 Monterey ARM64/M1 platform

---

configs/components/cpp-hocon.rb
configs/components/cpp-pcp-client.rb
configs/components/leatherman.rb
configs/components/pxp-agent.rb
configs/components/runtime.rb
configs/platforms/ubuntu-16.04-amd64.rb
configs/platforms/ubuntu-16.04-i386.rb
configs/projects/pxp-agent.rb

Ubuntu 16.04 hit end-of-life in April 2021. This commit removes Ubuntu 16.04 from all Vanagon platforms, components, and projects.

(PA-4515) Removes Ubuntu 16.04

---

configs/components/cpp-hocon.rb
configs/components/cpp-pcp-client.rb
configs/components/leatherman.rb
configs/components/pxp-agent.rb
configs/components/runtime.rb
configs/platforms/debian-9-amd64.rb
configs/platforms/debian-9-i386.rb
configs/projects/pxp-agent.rb

Debian 9 ("stretch") hit end the end of its LTS support in June
2022. This commit removes Debian 9 from all Vanagon platforms, components, and projects.

(PA-4574) Removes Debian 9 from Vanagon config

---

.github/workflows/checks.yaml

GitHub is deprecating Ubuntu 18.04 runners on April 1, 2023. This commit switches all Ubuntu 18.04 used in GitHub Actions to ubuntu-latest (currently Ubuntu 20.04).

(PA-4663) Updates Ubuntu GitHub Action runners

---

configs/components/leatherman.rb
configs/components/pxp-agent.rb

Solaris-11-sparc somehow has `libgcc_s.so` already in its path. With the recent fix for solaris-10-sparc we are now declaring `libgcc_s.so` twice, and that produces an error at compliation time.
This PR simply doesn't apply that library for solaris-11-sparc.

(maint) Fix solaris-11-sparc libraries

---

configs/components/pxp-agent.rb

Solaris-10-x86_64, and both versions of solaris-11 already have `libgcc_s.so` in the path. So we only want to add that for solaris-10-sparc.

(maint) Solaris-10 non sparc fix

---

configs/platforms/osx-11-x86_64.rb
configs/platforms/osx-12-arm64.rb
configs/platforms/osx-12-x86_64.rb

This commit removes the plat.output_dir command from  macOS 11 (x86) and 12 (x86 & arm) platform definitions since pxp-agent-vanagon does not have that file structure, everything is stored under the artifacts directory on builds.delivery.puppetlabs.net

(maint) Remove output directory command

---

configs/platforms/osx-11-arm64.rb
configs/platforms/osx-11-x86_64.rb
configs/platforms/osx-12-arm64.rb
configs/platforms/osx-12-x86_64.rb

See VANAGON-214
Remove `plat.output_dir` as we determined it wasn't required in main and likely earlier branches.

(maint) Inherit macOS platform defaults from vanagon

---

configs/components/pl-cmake-patch.rb
configs/projects/pxp-agent.rb
patches/cmake/0001-FindOpenSSL-Tolerate-tabs-in-header-while-parsing-ve.patch
patches/cmake/0002-FindOpenSSL-Do-not-assume-that-the-version-regex-fin.patch
patches/cmake/0003-FindOpenSSL-Detect-OpenSSL-3.0.0.patch
patches/cmake/0004-FindOpenSSL-Fix-OpenSSL-3.0.0-version-extraction.patch

OpenSSL 3 introduced a new versioning scheme. CMake < 3.18 doesn't
understand the new scheme and will fail to `FindOpenSSL`.
Additionally, the version of CMake installed via chocolatey on Windows contains
\r\n line endings, so perform unix2dos on Windows when patching. We use awk
because it's already installed, while dos2unix is not.
Built [pxp-agent-vanagon#5487502e7](https://jenkins-platform.delivery.puppetlabs.net/view/vanagon-generic-builder/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/1972/) using `agent-runtime-main#202303080`
Running [`puppet-agent#30bd0c8340428814ab9d6f930cfe2cc954d3b80c` adhoc](https://jenkins-platform.delivery.puppetlabs.net/view/puppet-agent/view/ad-hoc/job/platform_puppet-agent-extra_puppet-agent-packaging_adhoc-ad_hoc/1273/) with …

(PA-4870) Patch cmake for OpenSSL 3

---

configs/components/leatherman.rb

Leatherman relies on a deprecated CURLOPT_PROTOCOLS constant, ignore for now.

(PA-5393) Don't warn about leatherman deprecation declarations 7.x

---

configs/components/leatherman.rb

Leatherman relies on a deprecated CURLOPT_PROTOCOLS constant, ignore for now.

(PA-5393) Don't warn about leatherman deprecation declarations main

---

configs/components/leatherman.rb
configs/components/pxp-agent.rb

It's no longer necessary to disable dynamicbase with OpenSSL 3 on Windows FIPS.
Blocked on https://github.com/puppetlabs/puppet-runtime/pull/670

(PA-5427) Enable dynamicbase on Windows FIPS

---

configs/platforms/windows-2012r2-x64.rb
configs/platforms/windows-2012r2-x86.rb
configs/platforms/windowsfips-2012r2-x64.rb

Chocolatey 2.0 dropped the deprecated Get-BinRoot script which mingw-w64 relies on, so pin back to 1.4.0 for now. We also have to disable upgrades so we don't upgrade to 2.0.
Passed in https://jenkins-platform.delivery.puppetlabs.net/view/vanagon-generic-builder/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/2069/

(PA-5593) Pin to chocolatey 1.4.0

---

configs/platforms/aix-7.2-ppc.rb

Whenver a fileset is installed via installp, e.g. openssl.base, IBM recommends running updtvpkg so that RPM packages which depend on it, build correctly.
See also puppetlabs/puppet-runtime@a46d6e1d33ca748de66f76c915df625cb1e1ded2
Built https://jenkins-platform.delivery.puppetlabs.net/view/vanagon-generic-builder/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/2138/BUILD_TARGET=aix-7.2-ppc,SLAVE_LABEL=k8s-worker/

(PA-5644) Use yum update on AIX

---

configs/platforms/debian-11-aarch64.rb

The pxp-agent build for debian-11-arm64 7.x stream is available here: https://builds.delivery.puppetlabs.net/pxp-agent/6880a86739aef76056c74057b4e089a0acfd8c9d/artifacts/?C=M&O=D
The jenkins job to build it was this: https://jenkins-platform.delivery.puppetlabs.net/view/vanagon-generic-builder/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/2392/

(PA-4608) Add debian-11-aarch64 platform definition file

---

configs/platforms/debian-11-aarch64.rb

The pxp-agent build for debian-11-arm64 main stream is available here: https://builds.delivery.puppetlabs.net/pxp-agent/2dc1f4d072c110a8fdc13270216e4a5be79b52c9/artifacts/?C=M&O=D
The jenkins job to build it was this: https://jenkins-platform.delivery.puppetlabs.net/view/vanagon-generic-builder/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/2393/

(PA-5742) Add the debian-11 (ARM64) definition file to main stream

---

configs/platforms/amazon-2023-aarch64.rb
configs/platforms/amazon-2023-x86_64.rb

* Build: [platform_vanagon-generic-builder_vanagon-packaging_generic-builder](https://jenkins-platform.delivery.puppetlabs.net/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/BUILD_TARGET=amazon-2023-aarch64,SLAVE_LABEL=k8s-worker/2479/console
)
* Artifact: [amazon-2023-aarch64.tar.gz](http://builds.delivery.puppetlabs.net/pxp-agent/6a94c5f0932c4533ae63581457b48ebcd40a822a/artifacts/pxp-agent-202308310.27.g6a94c5f.amazon-2023-aarch64.tar.gz)
* Build: [platform_vanagon-generic-builder_vanagon-packaging_generic-builder](https://jenkins-platform.delivery.puppetlabs.net/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/BUILD_TARGET=amazon-2023-x86_64,SLAVE_LABEL=k8s-worker/2480/console
)
* Artifact: …

(PA-5569) Amazon Linux 2023 platform definition to pxp-agent-vanagon

---

configs/platforms/osx-14-x86_64.rb

Artifact:
https://builds.delivery.puppetlabs.net/pxp-agent/1f9e4f52cc5ab1e40f9e2b82c3e644b30c645a97/artifacts/?C=M&O=D

(PA-5879) Add macOS 14 (Intel) platform definition to pxp-agent-vanagon-main

---

configs/platforms/debian-11-amd64.rb
configs/platforms/debian-12-aarch64.rb
configs/platforms/debian-12-amd64.rb

successful builds for amd64 and aarch64 [vanagon generic builder pxp-agent](https://jenkins-platform.delivery.puppetlabs.net/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/2556/)
will drop build test commit before merge

(PA-5552) debian 12 platforms for main

---

configs/platforms/debian-11-amd64.rb
configs/platforms/debian-12-aarch64.rb
configs/platforms/debian-12-amd64.rb

successful builds for amd64 and aarch64 [vanagon generic builder pxp-agent](https://jenkins-platform.delivery.puppetlabs.net/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/2557/)
will drop build test commit before merge

(PA-5552) debian 12 platforms for 7.x

---

configs/platforms/osx-14-arm64.rb

Add MacOS14 ARM platform definition 
[Vanagon Generic builder](https://jenkins-platform.delivery.puppetlabs.net/view/vanagon-generic-builder/job/platform_vanagon-generic-builder_vanagon-packaging-ship-repos_generic-builder/1341/)

(PA-5906) Add macos14 arm definition 7.x

---

.github/workflows/checks.yaml
.rubocop.yml
Gemfile
Rakefile
configs/components/puppet-runtime.rb
configs/platforms/solaris-10-i386.rb
configs/platforms/solaris-10-sparc.rb
configs/platforms/solaris-11-sparc.rb

Recently, the checks action began failing because a newer version of Bundler (2.5.0) removed support for Ruby 2.6 and 2.7. Because the checks action runs on Ruby 2.7, the action started to fail.
This commit:
- Updates the Ruby version from 2.7 to 3.0.
- Unpins Rubocop from a three-year-old verison.
- Updates Rubocop's TargetRubyVersion from 2.4 to 2.6.
- Addresses minor style offenses found by the updated Rubocop.
- Removes the commit summary check, as Puppet no longer has a public Jira instance.

Update checks action

---

configs/components/cpp-hocon.rb
configs/components/cpp-pcp-client.rb
configs/components/leatherman.rb
configs/components/pxp-agent.rb
configs/platforms/sles-11-x86_64.rb

- Add SLES-11 (Intel) platform definition file
- SLES-11 uses pl-autotools instead of automake and autoconf since puppet7 uses ruby 2 which is not compatible with the supported version of autoconf and automake for SLES-11.
- Make cpp-pcp-client, leatherman and pxp-agent components to use the default pl-build-tools.
- SLES-11 does not require the runtime component since it only adds pl-gcc for it which we already do in its platform definition file.
- Due to compatibility reasons pl-gcc and pl-cmake have been manually downgraded in the platform definition file.

(PA-6002) Add SLES-11 (Intel) support

---

configs/components/cpp-hocon.rb
configs/components/cpp-pcp-client.rb
configs/components/leatherman.rb
configs/components/pxp-agent.rb
configs/components/runtime.rb
configs/platforms/sles-11-x86_64.rb
configs/projects/pxp-agent.rb

vanagon pipeline : https://jenkins-platform.delivery.puppetlabs.net/job/platform_vanagon-generic-builder_vanagon-packaging-ship-repos_generic-builder/1453/console

(PA-6001) Add sles11 platform to pxp-agent

---

configs/platforms/el-9-ppc64le.rb

Added platform `el-9-ppc64le` to pxp-agent

(PA-6377): Added el-9-ppc64le to pxp-agent

---

configs/platforms/amazon-7-aarch64.rb

Build: [amazon-7-aarch64](https://jenkins-platform.delivery.puppetlabs.net/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/BUILD_TARGET=amazon-7-aarch64,SLAVE_LABEL=k8s-worker/2919/consoleFull)
[artifacts](https://builds.delivery.puppetlabs.net/pxp-agent/e1f258d30329ae8887e4f0555ceac2f6c73c5e8e/artifacts/)

(PA-6262) Add Amazon Linux2 platform definition to pxp-agent-vanagon-main

---

configs/components/cpp-hocon.rb
configs/components/cpp-pcp-client.rb
configs/components/leatherman.rb
configs/components/pxp-agent.rb

In Amazon Linux 2, when we install cmake3, it creates a cmake3 executable instead of cmake. Therefore, in this PR, we're adding a condition specifically for the cmake executable on Amazon Linux 2.
Build [amazon-7-aarch64](https://jenkins-platform.delivery.puppetlabs.net/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/BUILD_TARGET=amazon-7-aarch64,SLAVE_LABEL=k8s-worker/2934/consoleFull)
Artifacts [pxp-agent](http://builds.delivery.puppetlabs.net/pxp-agent/550885d5786628c472c477d7da117485e6c21bfb/artifacts/)

(PA-6262) Bumping up cmake version to 3 for amazon-7-aarch64 main

---

configs/components/cpp-hocon.rb
configs/components/cpp-pcp-client.rb
configs/components/leatherman.rb
configs/components/pxp-agent.rb
configs/platforms/amazon-7-aarch64.rb

AL2 platform definition added for 7.x
vanagon generic builder : https://jenkins-platform.delivery.puppetlabs.net/view/vanagon-generic-builder/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/2938/

(PA-6263) Add amazon linux2 to pxp-agent 7.x and bump cmake

---

configs/components/cpp-hocon.rb
configs/components/cpp-pcp-client.rb
configs/components/leatherman.rb
configs/components/pxp-agent.rb
configs/platforms/amazon-2-aarch64.rb
configs/platforms/amazon-7-aarch64.rb

Amazon 7 is an implementation detail, the actual OS is named Amazon 2
(cherry picked from commit 6bf00a03927893aec3a646a661eab79267021434)

[Backport 7.x] Rename Amazon 7 to 2
